// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    doctype(5);
    return html(function() {
      head(function() {
        title('Codebook Generator');
        script({
          src: '//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'
        });
        return script({
          src: './codebook/script.js'
        });
      });
      return body;
    });
  };

}).call(this);
