// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var codebook, key, message, print, value, word, words, _i, _len, _ref, _results;
    words = ["hello", "world", "test", "fun", "toodles"];
    message = prompt("Message:");
    codebook = {};
    _ref = message.split(/\b/);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      word = _ref[_i];
      if (!/\W/.test(word)) {
        if (codebook[word] == null) {
          codebook[word] = words[Math.floor(Math.random() * words.length)];
        }
        message.replace(new RegExp("(\\b)" + word + "(\\b)", "g"), "$1" + codebook[word] + "$2");
      }
    }
    print = function(text) {
      return $(document.createElement("p")).text(text).appendTo(document.body);
    };
    print(message);
    print("Codebook:");
    _results = [];
    for (key in codebook) {
      value = codebook[key];
      _results.push(print("\"" + value + "\" means \"" + key + "\""));
    }
    return _results;
  });

}).call(this);
